"""
Provider-agnostic LLM client with an on-disk response cache.

Never called from business logic directly — core/obligation/compiler.py is the
only caller in the project, and it receives a client by injection so tests can
supply a recorded one.

CREDENTIALS
-----------
Read from the environment (via a .env file loaded at import) at CLIENT
CONSTRUCTION ONLY. A key is never read inside business logic, never logged,
never placed in a cache key, and never included in an exception message. If the
required variable is absent, construction fails with a message naming the file
to create — it does not fall back to an unauthenticated call that fails later
with a stack trace into SDK internals.

DETERMINISM
-----------
Two mechanisms, and both are needed:

  1. `temperature=0` on providers that still accept it (Groq/OpenAI-compatible).
     Note that Anthropic REMOVED sampling parameters on Opus 5 / Sonnet 5 /
     Opus 4.6+ — a request carrying `temperature` there is rejected with a 400 —
     so AnthropicProvider deliberately does not send one. That asymmetry is why
     temperature lives on the request and is applied per-provider rather than
     being a single global setting.

  2. The on-disk cache, keyed by sha256 over
     (provider, model, system, prompt, max_tokens, temperature, effort,
     prompt_version).

     THE MODEL AND TEMPERATURE ARE PART OF THE KEY. Without them, switching
     provider or model would silently replay responses generated by the old one
     under the new one's name and corrupt every downstream metric. The cache
     directory is committed, so once a run is recorded, CI and reviewers
     reproduce the exact bytes the published numbers came from — with no
     credential and no spend. CacheOnlyProvider makes that enforceable by
     raising on a miss instead of falling through to a live call.
"""

from __future__ import annotations

import dataclasses
import hashlib
import json
import os
import random
import re
import time
from decimal import Decimal
from pathlib import Path
from typing import Protocol

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CACHE_DIR = REPO_ROOT / "eval" / "llm_cache"


def _load_dotenv() -> None:
    """Load .env if python-dotenv is available. Absence is not an error: the
    environment may already carry the variables (CI, exported shell vars)."""
    try:
        from dotenv import load_dotenv
    except ImportError:
        return
    load_dotenv(REPO_ROOT / ".env", override=False)


_load_dotenv()


# ── Model registry ────────────────────────────────────────────────────────
#
# `verified` records whether the price was confirmed against the provider's
# published rate card. An unverified price still produces a cost figure, but
# every report carries the flag so a number is never presented as authoritative
# when it isn't. Guessing silently would be worse than saying "unverified".

@dataclasses.dataclass(frozen=True)
class ModelPricing:
    input_usd_per_mtok:  Decimal
    output_usd_per_mtok:  Decimal
    verified:              bool
    source_note:            str


MODEL_PRICING: dict[str, ModelPricing] = {
    # Anthropic — verified against the bundled model/pricing reference 2026-08-29.
    "claude-opus-5":    ModelPricing(Decimal("5.00"), Decimal("25.00"), True, "Anthropic list price"),
    "claude-sonnet-5":  ModelPricing(Decimal("2.00"), Decimal("10.00"), True, "Anthropic list price"),
    "claude-haiku-4-5": ModelPricing(Decimal("1.00"), Decimal("5.00"), True, "Anthropic list price"),

    # Groq — verified 2026-09-01 against published on-demand rates
    # (cloudzero.com/blog/groq-pricing, openrouter.ai/openai/gpt-oss-120b).
    "openai/gpt-oss-120b": ModelPricing(
        Decimal("0.15"), Decimal("0.60"), True,
        "Groq on-demand rate, verified 2026-09-01",
    ),
    "openai/gpt-oss-20b": ModelPricing(
        Decimal("0.10"), Decimal("0.50"), False,
        "PLACEHOLDER — verify at https://groq.com/pricing before publishing",
    ),
}

DEFAULT_GROQ_MODEL = "openai/gpt-oss-120b"
DEFAULT_ANTHROPIC_MODEL = "claude-opus-5"
DEFAULT_MODEL = DEFAULT_GROQ_MODEL

# USD -> INR, frozen so a reported rupee figure is reproducible rather than
# drifting between runs. Update deliberately and re-run; never read a live rate
# inside an eval.
USD_TO_INR = Decimal("88.0")


class LLMError(Exception):
    """Any failure reaching or parsing a provider response."""


class CacheMiss(LLMError):
    """Raised by CacheOnlyProvider when a request is not in the cache."""


class MissingCredential(LLMError):
    """A provider was selected but its credential is not set."""


class RateLimited(LLMError):
    """Retries were exhausted against a rate-limited provider."""


@dataclasses.dataclass(frozen=True)
class LLMResponse:
    text:            str
    input_tokens:     int
    output_tokens:     int
    model:              str
    from_cache:          bool
    latency_seconds:      float

    def pricing(self) -> ModelPricing:
        if self.model not in MODEL_PRICING:
            raise LLMError(
                f"No pricing entry for model {self.model!r}. Add it to MODEL_PRICING "
                f"rather than guessing a cost."
            )
        return MODEL_PRICING[self.model]

    def cost_usd(self) -> Decimal:
        p = self.pricing()
        million = Decimal("1000000")
        return (Decimal(self.input_tokens) / million) * p.input_usd_per_mtok + (
            Decimal(self.output_tokens) / million
        ) * p.output_usd_per_mtok

    def cost_inr(self) -> Decimal:
        return self.cost_usd() * USD_TO_INR


@dataclasses.dataclass(frozen=True)
class LLMRequest:
    system:          str
    prompt:           str
    max_tokens:        int = 8192
    temperature:        float = 0.0
    effort:              str = "medium"
    prompt_version:       str = "unversioned"
    model:                 str = DEFAULT_MODEL


class LLMProvider(Protocol):
    name: str

    def complete(self, request: LLMRequest) -> LLMResponse: ...


# ── Cache key ─────────────────────────────────────────────────────────────

def cache_key(provider_name: str, request: LLMRequest) -> str:
    """
    Stable sha256 over every input that can change the response.

    `model` and `temperature` are included deliberately: without them, swapping
    provider or model would replay the previous model's responses under the new
    model's name, silently corrupting every metric computed from them. Never
    includes a credential.
    """
    payload = {
        "provider": provider_name,
        "model": request.model,
        "system": request.system,
        "prompt": request.prompt,
        "max_tokens": request.max_tokens,
        "temperature": request.temperature,
        "effort": request.effort,
        "prompt_version": request.prompt_version,
    }
    blob = json.dumps(payload, sort_keys=True, ensure_ascii=True)
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()


# ── Retry ─────────────────────────────────────────────────────────────────

MAX_RETRIES = 6
BASE_DELAY_SECONDS = 2.0
MAX_DELAY_SECONDS = 60.0


def _backoff_delay(attempt: int, rng: random.Random) -> float:
    """Exponential backoff with full jitter, capped.

    Full jitter (uniform over [0, computed]) rather than fixed backoff, because
    the eval fires ~950 requests in a tight loop: without jitter every retry
    from a burst re-collides at the same instant and the rate limit never
    clears."""
    ceiling = min(BASE_DELAY_SECONDS * (2 ** attempt), MAX_DELAY_SECONDS)
    return rng.uniform(0.0, ceiling)


def _retry_after_seconds(exc: Exception) -> float | None:
    """Honour a provider-supplied Retry-After header when present."""
    response = getattr(exc, "response", None)
    headers = getattr(response, "headers", None)
    if not headers:
        return None
    raw = headers.get("retry-after") or headers.get("Retry-After")
    if raw is None:
        return None
    try:
        return float(raw)
    except (TypeError, ValueError):
        return None


# ── Providers ─────────────────────────────────────────────────────────────

class GroqProvider:
    """
    Groq, OpenAI-compatible chat-completions surface.

    Open weights by design, not by economy — see README. The clearing layer's
    safety comes from floor enforcement, not from model quality, so running the
    compiler on an open-weights model is evidence for the architecture rather
    than a compromise on it.
    """

    name = "groq"

    def __init__(self, api_key: str | None = None, min_interval_seconds: float = 0.0) -> None:
        # Adaptive pacing. Starts at 0 so a fast tier is never slowed
        # artificially, and self-tunes upward the first time a token rate limit
        # is hit. This matters because the eval fires a tight loop of ~31
        # requests: without pacing, every request after the first few fails,
        # burns retries, and the run takes longer than if it had simply waited.
        self._min_interval = max(
            min_interval_seconds,
            float(os.environ.get("SANKALP_GROQ_MIN_INTERVAL", "0") or 0),
        )
        self._last_call_at = 0.0
        try:
            from groq import Groq
        except ImportError as exc:   # pragma: no cover - depends on install
            raise LLMError(
                "The `groq` package is not installed. Install it with `pip install groq`, "
                "or set SANKALP_LLM_PROVIDER=cache_only to replay the committed cache."
            ) from exc

        key = api_key or os.environ.get("GROQ_API_KEY")
        if not key or key == "REPLACE_ME":
            raise MissingCredential(
                "GROQ_API_KEY is not set.\n"
                "  1. Copy the template:  copy .env.example .env   (cmd.exe)\n"
                "                         cp .env.example .env     (bash)\n"
                "  2. Put your key in .env as:  GROQ_API_KEY=<your key>\n"
                "     Get one at https://console.groq.com/keys\n"
                "  .env is gitignored and must never be committed.\n"
                "To run with no credential at all, replay the committed cache:\n"
                "  python -m eval.compiler_harness --cache-only"
            )
        self._client = Groq(api_key=key)

    def _respect_pacing(self) -> None:
        """Wait out the self-tuned minimum interval before calling."""
        if self._min_interval <= 0:
            return
        elapsed = time.monotonic() - self._last_call_at
        if elapsed < self._min_interval:
            time.sleep(self._min_interval - elapsed)
        self._last_call_at = time.monotonic()

    def _slow_down(self, exc: Exception) -> None:
        """
        Widen the inter-request interval after a token rate limit.

        Derived from the account's actual limit when the error reports it —
        if one request reserves R tokens against a budget of L per minute, the
        sustainable rate is 60*R/L seconds apart. Falls back to a flat step
        when the error doesn't carry numbers. Only ever increases, so a run
        settles at the tier's real throughput instead of oscillating.
        """
        parsed = parse_token_limit(exc)
        if parsed:
            limit, requested = parsed
            interval = 60.0 * requested / max(limit, 1)
        else:
            interval = self._min_interval + 15.0
        self._min_interval = min(max(self._min_interval, interval), 120.0)

    def complete(self, request: LLMRequest) -> LLMResponse:
        started = time.perf_counter()
        rng = random.Random(0)   # jitter only; does not affect model output
        completion = None
        last_exc: Exception | None = None

        for attempt in range(MAX_RETRIES):
            self._respect_pacing()
            try:
                completion = self._client.chat.completions.create(
                    model=request.model,
                    messages=[
                        {"role": "system", "content": request.system},
                        {"role": "user", "content": request.prompt},
                    ],
                    temperature=request.temperature,
                    max_completion_tokens=request.max_tokens,
                    reasoning_effort=request.effort,
                    stream=False,
                )
                break
            except Exception as exc:                      # noqa: BLE001 - classified below
                if request_can_never_fit(exc):
                    limit, requested = parse_token_limit(exc)   # type: ignore[misc]
                    raise LLMError(
                        f"Request reserves {requested} tokens but the account's entire "
                        f"per-minute budget is {limit}. Waiting cannot fix this — the "
                        f"request must get smaller.\n"
                        f"  The reservation is (prompt tokens + max_tokens), so lower "
                        f"max_tokens:\n"
                        f"      python -m eval.compiler_harness --limit-seeds 3 "
                        f"--max-tokens {max(512, limit - (requested - request.max_tokens) - 256)}\n"
                        f"  Current max_tokens={request.max_tokens}, prompt is roughly "
                        f"{requested - request.max_tokens} tokens.\n"
                        f"  Or raise the limit at https://console.groq.com/settings/billing"
                    ) from exc

                if not _is_retryable(exc):
                    # A malformed request fails identically on every retry;
                    # retrying burns quota and delays a clear error.
                    raise LLMError(f"Groq request failed: {type(exc).__name__}: {exc}") from exc

                last_exc = exc
                self._slow_down(exc)
                if attempt < MAX_RETRIES - 1:
                    time.sleep(_retry_after_seconds(exc) or _backoff_delay(attempt, rng))

        if completion is None:
            raise RateLimited(
                f"Groq rate limit not cleared after {MAX_RETRIES} attempts. "
                f"Last error: {type(last_exc).__name__}: {last_exc}. "
                f"Free-tier limits bite on the full train run — wait and re-run "
                f"(the cache keeps completed work, so a resume only fetches what is "
                f"missing), or use --limit-seeds to shrink the batch."
            ) from last_exc

        choice = completion.choices[0]
        text = choice.message.content or ""
        if not text.strip():
            raise LLMError(
                f"Groq returned no content (finish_reason={choice.finish_reason!r}). "
                f"If finish_reason is 'length', raise max_completion_tokens."
            )

        usage = completion.usage
        return LLMResponse(
            text=text,
            input_tokens=getattr(usage, "prompt_tokens", 0) or 0,
            output_tokens=getattr(usage, "completion_tokens", 0) or 0,
            model=request.model,
            from_cache=False,
            latency_seconds=time.perf_counter() - started,
        )


_TPM_RE = re.compile(r"Limit\s+(\d+),\s*Requested\s+(\d+)", re.IGNORECASE)


def parse_token_limit(exc: Exception) -> tuple[int, int] | None:
    """Extract (limit, requested) from a Groq token rate-limit error, if present."""
    match = _TPM_RE.search(str(exc))
    if not match:
        return None
    return int(match.group(1)), int(match.group(2))


def request_can_never_fit(exc: Exception) -> bool:
    """
    True when a single request reserves more tokens than the account's entire
    per-minute budget.

    This distinction matters: an ordinary rate limit clears if you wait, but a
    request larger than the whole TPM budget will fail identically forever.
    Retrying it burns six attempts and ~two minutes to arrive at the same
    error, so it must fail fast with a fix the caller can actually apply
    (lower max_tokens) rather than be treated as transient.
    """
    parsed = parse_token_limit(exc)
    return parsed is not None and parsed[1] > parsed[0]


def _is_retryable(exc: Exception) -> bool:
    """
    Rate limits and transient server errors are retryable; a malformed request
    is not, and neither is a request too large to ever fit.

    Note 413: Groq returns token-budget rate limits as HTTP 413 with
    `code: rate_limit_exceeded`, not 429. Treating 413 as a plain "payload too
    large" client error would make every genuine TPM exhaustion permanent.
    """
    if request_can_never_fit(exc):
        return False

    status = getattr(exc, "status_code", None) or getattr(
        getattr(exc, "response", None), "status_code", None
    )
    if status is not None:
        if status in (429, 413):
            return True
        return bool(status >= 500)
    name = type(exc).__name__.lower()
    return any(marker in name for marker in ("ratelimit", "timeout", "connection", "apiconnection"))


class AnthropicProvider:
    """
    Anthropic Messages API.

    Deliberately sends NO `temperature`, `top_p`, `top_k` (removed on current
    models — a 400) and no `budget_tokens` (removed on Opus 5; adaptive thinking
    replaces it). Depth is controlled by `output_config.effort`. Kept working so
    the provider swap stays reversible.
    """

    name = "anthropic"

    def __init__(self, api_key: str | None = None) -> None:
        try:
            import anthropic
        except ImportError as exc:   # pragma: no cover
            raise LLMError(
                "The `anthropic` package is not installed. Install it with "
                "`pip install anthropic`, or set SANKALP_LLM_PROVIDER=cache_only."
            ) from exc
        self._anthropic = anthropic
        key = api_key or os.environ.get("ANTHROPIC_API_KEY")
        if key == "REPLACE_ME":
            key = None
        # A bare client also resolves an `ant auth login` profile, so an unset
        # env var is not necessarily "no credentials" — let the SDK decide, and
        # translate its unhelpful failure below.
        self._client = anthropic.Anthropic(api_key=key) if key else anthropic.Anthropic()

    def complete(self, request: LLMRequest) -> LLMResponse:
        started = time.perf_counter()
        effort = request.effort if request.effort in ("low", "medium", "high", "xhigh", "max") else "high"
        try:
            response = self._client.messages.create(
                model=request.model,
                max_tokens=request.max_tokens,
                system=request.system,
                output_config={"effort": effort},
                messages=[{"role": "user", "content": request.prompt}],
            )
        except self._anthropic.APIStatusError as exc:
            raise LLMError(f"Anthropic API error ({exc.status_code}): {exc}") from exc
        except self._anthropic.APIConnectionError as exc:
            raise LLMError(f"Could not reach the Anthropic API: {exc}") from exc
        except TypeError as exc:
            if "authentication" in str(exc).lower():
                raise MissingCredential(
                    "ANTHROPIC_API_KEY is not set.\n"
                    "  1. Copy the template:  copy .env.example .env   (cmd.exe)\n"
                    "                         cp .env.example .env     (bash/zsh)\n"
                    "                         Copy-Item .env.example .env  (PowerShell)\n"
                    "  2. Add to .env:  ANTHROPIC_API_KEY=<your key>\n"
                    "     or run `ant auth login`.\n"
                    "Note: this project defaults to Groq. You only need this if you set\n"
                    "SANKALP_LLM_PROVIDER=anthropic.\n"
                    "To run with no credential at all, replay the committed cache:\n"
                    "  python -m eval.compiler_harness --cache-only"
                ) from exc
            raise LLMError(
                f"Anthropic SDK rejected the request parameters: {exc}. Usually means "
                f"the installed SDK version does not accept a parameter this client "
                f"sends (currently: output_config)."
            ) from exc

        if response.stop_reason == "refusal":
            raise LLMError(f"Model refused the request. stop_details={getattr(response, 'stop_details', None)!r}")

        text = "".join(block.text for block in response.content if block.type == "text")
        if not text.strip():
            raise LLMError(f"Model returned no text (stop_reason={response.stop_reason!r}).")

        return LLMResponse(
            text=text,
            input_tokens=response.usage.input_tokens,
            output_tokens=response.usage.output_tokens,
            model=response.model,
            from_cache=False,
            latency_seconds=time.perf_counter() - started,
        )


class CacheOnlyProvider:
    """
    Replays a committed cache and refuses to make network calls.

    Takes the provider namespace it is replaying, so a cache recorded under
    `groq` is replayed under `groq` and its keys match. Hardcoding a namespace
    here would make a cross-provider replay silently miss every entry.
    """

    def __init__(self, name: str = "groq") -> None:
        self.name = name

    def complete(self, request: LLMRequest) -> LLMResponse:
        raise CacheMiss(
            "CacheOnlyProvider: request is not in the committed cache "
            f"(provider={self.name!r}, model={request.model!r}, "
            f"prompt_version={request.prompt_version!r}). Either the prompt, model, "
            "temperature or provider changed since the cache was recorded, or the "
            "cache was not committed. Re-record with a live provider, or restore "
            "eval/llm_cache/."
        )


# ── Client ────────────────────────────────────────────────────────────────

class LLMClient:
    """Wraps a provider with an on-disk, content-addressed response cache."""

    def __init__(
        self,
        provider: LLMProvider,
        cache_dir: Path | None = None,
        *,
        read_cache: bool = True,
        write_cache: bool = True,
    ) -> None:
        self.provider = provider
        self.cache_dir = Path(cache_dir) if cache_dir is not None else DEFAULT_CACHE_DIR
        self.read_cache = read_cache
        self.write_cache = write_cache
        self.hits = 0
        self.misses = 0

    def _path_for(self, key: str) -> Path:
        return self.cache_dir / f"{key}.json"

    def _load(self, key: str) -> LLMResponse | None:
        path = self._path_for(key)
        if not path.exists():
            return None
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise LLMError(f"Corrupt LLM cache entry at {path}. Delete it and re-record.") from exc
        return LLMResponse(
            text=data["text"],
            input_tokens=data["input_tokens"],
            output_tokens=data["output_tokens"],
            model=data["model"],
            from_cache=True,
            latency_seconds=data.get("latency_seconds", 0.0),
        )

    def _store(self, key: str, request: LLMRequest, response: LLMResponse) -> None:
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        payload = {
            "text": response.text,
            "input_tokens": response.input_tokens,
            "output_tokens": response.output_tokens,
            "model": response.model,
            "latency_seconds": response.latency_seconds,
            # Recorded for auditability. Contains no credential — only the
            # request shape a reviewer needs to see which prompt produced this.
            "_request": {
                "provider": self.provider.name,
                "model": request.model,
                "system": request.system,
                "prompt": request.prompt,
                "max_tokens": request.max_tokens,
                "temperature": request.temperature,
                "effort": request.effort,
                "prompt_version": request.prompt_version,
            },
        }
        self._path_for(key).write_text(
            json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False), encoding="utf-8"
        )

    def complete(self, request: LLMRequest) -> LLMResponse:
        key = cache_key(self.provider.name, request)

        if self.read_cache:
            cached = self._load(key)
            if cached is not None:
                self.hits += 1
                return cached

        self.misses += 1
        response = self.provider.complete(request)
        if self.write_cache:
            self._store(key, request, response)
        return response


# ── Configuration ─────────────────────────────────────────────────────────

def build_provider(name: str | None = None) -> LLMProvider:
    """
    Select a provider by configuration, never by editing code.

    Order: explicit argument > SANKALP_LLM_PROVIDER env var > "groq".
    """
    selected = (name or os.environ.get("SANKALP_LLM_PROVIDER") or "groq").strip().lower()
    if selected == "groq":
        return GroqProvider()
    if selected == "anthropic":
        return AnthropicProvider()
    if selected in ("cache_only", "cache-only", "cache"):
        replay = (os.environ.get("SANKALP_CACHE_NAMESPACE") or "groq").strip().lower()
        return CacheOnlyProvider(replay)
    raise LLMError(
        f"Unknown provider {selected!r}. Set SANKALP_LLM_PROVIDER to one of: "
        f"groq | anthropic | cache_only"
    )


def default_model_for(provider_name: str) -> str:
    return {"groq": DEFAULT_GROQ_MODEL, "anthropic": DEFAULT_ANTHROPIC_MODEL}.get(
        provider_name, DEFAULT_GROQ_MODEL
    )


def default_client(*, cache_only: bool = False, provider: str | None = None) -> LLMClient:
    """
    Build the project's standard client. The model is a per-request field
    (LLMRequest.model), not a client setting, so the cache key always reflects
    the model that actually produced a response.
    """
    if cache_only:
        namespace = (provider or os.environ.get("SANKALP_LLM_PROVIDER") or "groq").strip().lower()
        if namespace in ("cache_only", "cache-only", "cache"):
            namespace = (os.environ.get("SANKALP_CACHE_NAMESPACE") or "groq").strip().lower()
        return LLMClient(CacheOnlyProvider(namespace))
    return LLMClient(build_provider(provider))
