"""
Versioned prompt templates, one file each.

A prompt's version string is part of the LLM cache key
(core/llm/client.cache_key), so editing a prompt file WITHOUT bumping its
version would silently reuse responses generated by the old wording — the
metrics would then describe a prompt that no longer exists. Bump the
version in the same commit as any edit to the prompt body.
"""

from __future__ import annotations

from pathlib import Path

PROMPTS_DIR = Path(__file__).resolve().parent


def load_prompt(name: str) -> str:
    path = PROMPTS_DIR / name
    if not path.exists():
        raise FileNotFoundError(
            f"Prompt template {name!r} not found in {PROMPTS_DIR}. "
            f"Available: {sorted(p.name for p in PROMPTS_DIR.glob('*.md'))}"
        )
    return path.read_text(encoding="utf-8")
