"""
Unit tests for core/llm/client.py.

No API key and no network. The point of these tests is the cache — which is
this project's determinism mechanism now that `temperature` no longer exists
on current Claude models (see the module docstring in core/llm/client.py).
"""

from __future__ import annotations

from decimal import Decimal

import pytest

from core.llm.client import (
    DEFAULT_MODEL,
    MODEL_PRICING_USD_PER_MTOK,
    USD_TO_INR,
    CacheMiss,
    CacheOnlyProvider,
    LLMClient,
    LLMError,
    LLMRequest,
    LLMResponse,
    cache_key,
)


class RecordingProvider:
    """Test double: returns a canned response and counts invocations."""

    name = "anthropic"

    def __init__(self, text: str = '{"ok": true}') -> None:
        self.text = text
        self.calls = 0

    def complete(self, request: LLMRequest) -> LLMResponse:
        self.calls += 1
        return LLMResponse(
            text=self.text, input_tokens=1000, output_tokens=200,
            model=request.model, from_cache=False, latency_seconds=0.5,
        )


def make_request(**overrides) -> LLMRequest:
    defaults = dict(system="sys", prompt="hello", max_tokens=1024,
                     effort="high", prompt_version="v1", model=DEFAULT_MODEL)
    defaults.update(overrides)
    return LLMRequest(**defaults)


class TestCacheKey:
    def test_identical_requests_share_a_key(self):
        assert cache_key("anthropic", make_request()) == cache_key("anthropic", make_request())

    def test_prompt_change_changes_key(self):
        assert cache_key("anthropic", make_request()) != cache_key(
            "anthropic", make_request(prompt="different")
        )

    def test_model_change_changes_key(self):
        assert cache_key("anthropic", make_request()) != cache_key(
            "anthropic", make_request(model="claude-sonnet-5")
        )

    def test_prompt_version_change_changes_key(self):
        """Editing a prompt without bumping its version would otherwise replay
        responses generated by the old wording."""
        assert cache_key("anthropic", make_request()) != cache_key(
            "anthropic", make_request(prompt_version="v2")
        )

    def test_effort_change_changes_key(self):
        assert cache_key("anthropic", make_request()) != cache_key(
            "anthropic", make_request(effort="low")
        )

    def test_key_is_hex_sha256(self):
        key = cache_key("anthropic", make_request())
        assert len(key) == 64
        assert all(c in "0123456789abcdef" for c in key)


class TestCaching:
    def test_first_call_hits_provider(self, tmp_path):
        provider = RecordingProvider()
        client = LLMClient(provider, cache_dir=tmp_path)
        client.complete(make_request())
        assert provider.calls == 1
        assert client.misses == 1

    def test_second_identical_call_is_served_from_cache(self, tmp_path):
        provider = RecordingProvider()
        client = LLMClient(provider, cache_dir=tmp_path)
        client.complete(make_request())
        response = client.complete(make_request())
        assert provider.calls == 1, "second call must not reach the provider"
        assert response.from_cache is True
        assert client.hits == 1

    def test_cached_text_matches_original(self, tmp_path):
        provider = RecordingProvider(text='{"value": 42}')
        client = LLMClient(provider, cache_dir=tmp_path)
        first = client.complete(make_request())
        second = client.complete(make_request())
        assert first.text == second.text

    def test_different_prompt_is_a_separate_entry(self, tmp_path):
        provider = RecordingProvider()
        client = LLMClient(provider, cache_dir=tmp_path)
        client.complete(make_request())
        client.complete(make_request(prompt="other"))
        assert provider.calls == 2

    def test_cache_survives_a_new_client_instance(self, tmp_path):
        """The reproducibility guarantee: a fresh process replays the cache."""
        provider_a = RecordingProvider()
        LLMClient(provider_a, cache_dir=tmp_path).complete(make_request())

        provider_b = RecordingProvider()
        response = LLMClient(provider_b, cache_dir=tmp_path).complete(make_request())
        assert provider_b.calls == 0
        assert response.from_cache is True

    def test_read_cache_false_forces_provider_call(self, tmp_path):
        provider = RecordingProvider()
        LLMClient(provider, cache_dir=tmp_path).complete(make_request())
        LLMClient(provider, cache_dir=tmp_path, read_cache=False).complete(make_request())
        assert provider.calls == 2

    def test_write_cache_false_does_not_persist(self, tmp_path):
        provider = RecordingProvider()
        client = LLMClient(provider, cache_dir=tmp_path, write_cache=False)
        client.complete(make_request())
        client.complete(make_request())
        assert provider.calls == 2

    def test_corrupt_cache_entry_raises_rather_than_silently_refetching(self, tmp_path):
        provider = RecordingProvider()
        client = LLMClient(provider, cache_dir=tmp_path)
        client.complete(make_request())
        entry = next(tmp_path.glob("*.json"))
        entry.write_text("not json", encoding="utf-8")
        with pytest.raises(LLMError, match="Corrupt LLM cache entry"):
            client.complete(make_request())

    def test_cache_entry_records_the_originating_request(self, tmp_path):
        """A reviewer must be able to see which prompt produced a cached
        response without re-running anything."""
        import json
        provider = RecordingProvider()
        LLMClient(provider, cache_dir=tmp_path).complete(make_request(prompt="traceable"))
        entry = json.loads(next(tmp_path.glob("*.json")).read_text(encoding="utf-8"))
        assert entry["_request"]["prompt"] == "traceable"


class TestCacheOnlyProvider:
    def test_raises_on_miss(self, tmp_path):
        client = LLMClient(CacheOnlyProvider(), cache_dir=tmp_path)
        with pytest.raises(CacheMiss, match="not in the committed cache"):
            client.complete(make_request())

    def test_replays_a_recorded_entry_without_network(self, tmp_path):
        LLMClient(RecordingProvider(text="recorded"), cache_dir=tmp_path).complete(make_request())
        response = LLMClient(CacheOnlyProvider(), cache_dir=tmp_path).complete(make_request())
        assert response.text == "recorded"
        assert response.from_cache is True

    def test_shares_cache_namespace_with_live_provider(self):
        """Recording live and replaying cache-only must produce the same key."""
        assert CacheOnlyProvider().name == RecordingProvider().name


class TestCost:
    def test_opus_5_cost_matches_published_rates(self):
        response = LLMResponse(text="", input_tokens=1_000_000, output_tokens=1_000_000,
                                model="claude-opus-5", from_cache=False, latency_seconds=0.0)
        assert response.cost_usd() == Decimal("30.00")   # $5 in + $25 out

    def test_zero_tokens_costs_nothing(self):
        response = LLMResponse(text="", input_tokens=0, output_tokens=0,
                                model="claude-opus-5", from_cache=False, latency_seconds=0.0)
        assert response.cost_usd() == Decimal("0")

    def test_inr_conversion_applies_the_frozen_rate(self):
        response = LLMResponse(text="", input_tokens=1_000_000, output_tokens=0,
                                model="claude-opus-5", from_cache=False, latency_seconds=0.0)
        assert response.cost_inr() == Decimal("5.00") * USD_TO_INR

    def test_unknown_model_raises_rather_than_guessing(self):
        response = LLMResponse(text="", input_tokens=10, output_tokens=10,
                                model="some-unreleased-model", from_cache=False, latency_seconds=0.0)
        with pytest.raises(LLMError, match="No pricing entry"):
            response.cost_usd()

    def test_default_model_has_pricing(self):
        assert DEFAULT_MODEL in MODEL_PRICING_USD_PER_MTOK
